# Generated by Django 5.1.3 on 2024-11-25 06:36

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransactionApp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='transaction',
            old_name='user_account',
            new_name='account',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='balance_after_transaction',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='description',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='transaction_date',
        ),
        migrations.AddField(
            model_name='transaction',
            name='is_approved',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw'), ('loan_request', 'Loan Request'), ('loan_approval', 'Loan Approval')], max_length=20),
        ),
        migrations.DeleteModel(
            name='LoanRequest',
        ),
    ]
