# Generated by Django 5.1.3 on 2024-11-26 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TransactionApp', '0003_transaction_updated_balance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('deposit', 'Deposit'), ('withdraw', 'Withdraw'), ('loan_request', 'Loan Request'), ('loan_approval', 'Loan Approval'), ('loan_paid', 'Loan Paid')], max_length=20),
        ),
    ]
