# Generated by Django 5.1.3 on 2024-11-21 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Accounts', '0002_remove_userbankinginformation_initial_deposit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userbankinginformation',
            name='profile_image',
            field=models.ImageField(blank=True, null=True, upload_to='accounts/profile_images/'),
        ),
    ]
